"""Added qr_token and qr_created_at to Patient

Revision ID: dd5acc9af4ef
Revises: ffd856eb5e45
Create Date: 2026-07-17 20:31:37.451445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5acc9af4ef'
down_revision = 'ffd856eb5e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('qr_created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_qr_token'), ['qr_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_qr_token'))
        batch_op.drop_column('qr_created_at')
        batch_op.drop_column('qr_token')

    # ### end Alembic commands ###
