/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MedicineRouteImport } from './routes/medicine'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolunteerIndexRouteImport } from './routes/volunteer/index'
import { Route as DoctorIndexRouteImport } from './routes/doctor/index'
import { Route as VolunteerQueueRouteImport } from './routes/volunteer/queue'
import { Route as VolunteerPatientsNewRouteImport } from './routes/volunteer/patients.new'
import { Route as VolunteerPatientsIdRouteImport } from './routes/volunteer/patients.$id'
import { Route as VolunteerCampsNewRouteImport } from './routes/volunteer/camps.new'
import { Route as DoctorConsultationIdRouteImport } from './routes/doctor/consultation.$id'

const MedicineRoute = MedicineRouteImport.update({
  id: '/medicine',
  path: '/medicine',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerIndexRoute = VolunteerIndexRouteImport.update({
  id: '/volunteer/',
  path: '/volunteer/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerQueueRoute = VolunteerQueueRouteImport.update({
  id: '/volunteer/queue',
  path: '/volunteer/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerPatientsNewRoute = VolunteerPatientsNewRouteImport.update({
  id: '/volunteer/patients/new',
  path: '/volunteer/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerPatientsIdRoute = VolunteerPatientsIdRouteImport.update({
  id: '/volunteer/patients/$id',
  path: '/volunteer/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerCampsNewRoute = VolunteerCampsNewRouteImport.update({
  id: '/volunteer/camps/new',
  path: '/volunteer/camps/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultationIdRoute = DoctorConsultationIdRouteImport.update({
  id: '/doctor/consultation/$id',
  path: '/doctor/consultation/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/medicine': typeof MedicineRoute
  '/volunteer/queue': typeof VolunteerQueueRoute
  '/doctor/': typeof DoctorIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/doctor/consultation/$id': typeof DoctorConsultationIdRoute
  '/volunteer/camps/new': typeof VolunteerCampsNewRoute
  '/volunteer/patients/$id': typeof VolunteerPatientsIdRoute
  '/volunteer/patients/new': typeof VolunteerPatientsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/medicine': typeof MedicineRoute
  '/volunteer/queue': typeof VolunteerQueueRoute
  '/doctor': typeof DoctorIndexRoute
  '/volunteer': typeof VolunteerIndexRoute
  '/doctor/consultation/$id': typeof DoctorConsultationIdRoute
  '/volunteer/camps/new': typeof VolunteerCampsNewRoute
  '/volunteer/patients/$id': typeof VolunteerPatientsIdRoute
  '/volunteer/patients/new': typeof VolunteerPatientsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/medicine': typeof MedicineRoute
  '/volunteer/queue': typeof VolunteerQueueRoute
  '/doctor/': typeof DoctorIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/doctor/consultation/$id': typeof DoctorConsultationIdRoute
  '/volunteer/camps/new': typeof VolunteerCampsNewRoute
  '/volunteer/patients/$id': typeof VolunteerPatientsIdRoute
  '/volunteer/patients/new': typeof VolunteerPatientsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/medicine'
    | '/volunteer/queue'
    | '/doctor/'
    | '/volunteer/'
    | '/doctor/consultation/$id'
    | '/volunteer/camps/new'
    | '/volunteer/patients/$id'
    | '/volunteer/patients/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/medicine'
    | '/volunteer/queue'
    | '/doctor'
    | '/volunteer'
    | '/doctor/consultation/$id'
    | '/volunteer/camps/new'
    | '/volunteer/patients/$id'
    | '/volunteer/patients/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/medicine'
    | '/volunteer/queue'
    | '/doctor/'
    | '/volunteer/'
    | '/doctor/consultation/$id'
    | '/volunteer/camps/new'
    | '/volunteer/patients/$id'
    | '/volunteer/patients/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MedicineRoute: typeof MedicineRoute
  VolunteerQueueRoute: typeof VolunteerQueueRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  VolunteerIndexRoute: typeof VolunteerIndexRoute
  DoctorConsultationIdRoute: typeof DoctorConsultationIdRoute
  VolunteerCampsNewRoute: typeof VolunteerCampsNewRoute
  VolunteerPatientsIdRoute: typeof VolunteerPatientsIdRoute
  VolunteerPatientsNewRoute: typeof VolunteerPatientsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/medicine': {
      id: '/medicine'
      path: '/medicine'
      fullPath: '/medicine'
      preLoaderRoute: typeof MedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/': {
      id: '/volunteer/'
      path: '/volunteer'
      fullPath: '/volunteer/'
      preLoaderRoute: typeof VolunteerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/queue': {
      id: '/volunteer/queue'
      path: '/volunteer/queue'
      fullPath: '/volunteer/queue'
      preLoaderRoute: typeof VolunteerQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/patients/new': {
      id: '/volunteer/patients/new'
      path: '/volunteer/patients/new'
      fullPath: '/volunteer/patients/new'
      preLoaderRoute: typeof VolunteerPatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/patients/$id': {
      id: '/volunteer/patients/$id'
      path: '/volunteer/patients/$id'
      fullPath: '/volunteer/patients/$id'
      preLoaderRoute: typeof VolunteerPatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/camps/new': {
      id: '/volunteer/camps/new'
      path: '/volunteer/camps/new'
      fullPath: '/volunteer/camps/new'
      preLoaderRoute: typeof VolunteerCampsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/consultation/$id': {
      id: '/doctor/consultation/$id'
      path: '/doctor/consultation/$id'
      fullPath: '/doctor/consultation/$id'
      preLoaderRoute: typeof DoctorConsultationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MedicineRoute: MedicineRoute,
  VolunteerQueueRoute: VolunteerQueueRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  VolunteerIndexRoute: VolunteerIndexRoute,
  DoctorConsultationIdRoute: DoctorConsultationIdRoute,
  VolunteerCampsNewRoute: VolunteerCampsNewRoute,
  VolunteerPatientsIdRoute: VolunteerPatientsIdRoute,
  VolunteerPatientsNewRoute: VolunteerPatientsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
