/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolunteerIndexRouteImport } from './routes/volunteer/index'
import { Route as VolunteerQueueRouteImport } from './routes/volunteer/queue'
import { Route as VolunteerPatientsNewRouteImport } from './routes/volunteer/patients.new'
import { Route as VolunteerCampsNewRouteImport } from './routes/volunteer/camps.new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerIndexRoute = VolunteerIndexRouteImport.update({
  id: '/volunteer/',
  path: '/volunteer/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerQueueRoute = VolunteerQueueRouteImport.update({
  id: '/volunteer/queue',
  path: '/volunteer/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerPatientsNewRoute = VolunteerPatientsNewRouteImport.update({
  id: '/volunteer/patients/new',
  path: '/volunteer/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerCampsNewRoute = VolunteerCampsNewRouteImport.update({
  id: '/volunteer/camps/new',
  path: '/volunteer/camps/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/volunteer/queue': typeof VolunteerQueueRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/volunteer/camps/new': typeof VolunteerCampsNewRoute
  '/volunteer/patients/new': typeof VolunteerPatientsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/volunteer/queue': typeof VolunteerQueueRoute
  '/volunteer': typeof VolunteerIndexRoute
  '/volunteer/camps/new': typeof VolunteerCampsNewRoute
  '/volunteer/patients/new': typeof VolunteerPatientsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/volunteer/queue': typeof VolunteerQueueRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/volunteer/camps/new': typeof VolunteerCampsNewRoute
  '/volunteer/patients/new': typeof VolunteerPatientsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/volunteer/queue'
    | '/volunteer/'
    | '/volunteer/camps/new'
    | '/volunteer/patients/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/volunteer/queue'
    | '/volunteer'
    | '/volunteer/camps/new'
    | '/volunteer/patients/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/volunteer/queue'
    | '/volunteer/'
    | '/volunteer/camps/new'
    | '/volunteer/patients/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  VolunteerQueueRoute: typeof VolunteerQueueRoute
  VolunteerIndexRoute: typeof VolunteerIndexRoute
  VolunteerCampsNewRoute: typeof VolunteerCampsNewRoute
  VolunteerPatientsNewRoute: typeof VolunteerPatientsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/': {
      id: '/volunteer/'
      path: '/volunteer'
      fullPath: '/volunteer/'
      preLoaderRoute: typeof VolunteerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/queue': {
      id: '/volunteer/queue'
      path: '/volunteer/queue'
      fullPath: '/volunteer/queue'
      preLoaderRoute: typeof VolunteerQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/patients/new': {
      id: '/volunteer/patients/new'
      path: '/volunteer/patients/new'
      fullPath: '/volunteer/patients/new'
      preLoaderRoute: typeof VolunteerPatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/camps/new': {
      id: '/volunteer/camps/new'
      path: '/volunteer/camps/new'
      fullPath: '/volunteer/camps/new'
      preLoaderRoute: typeof VolunteerCampsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  VolunteerQueueRoute: VolunteerQueueRoute,
  VolunteerIndexRoute: VolunteerIndexRoute,
  VolunteerCampsNewRoute: VolunteerCampsNewRoute,
  VolunteerPatientsNewRoute: VolunteerPatientsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
